# Generated by Django 5.1.5 on 2025-03-02 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='react',
            old_name='employee',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='react',
            name='department',
        ),
        migrations.AddField(
            model_name='react',
            name='detail',
            field=models.CharField(default='Default detail value', max_length=500),
            preserve_default=False,
        ),
    ]
